name: Request Review

on:
  issue_comment:
    types:
      - created

jobs:
  request-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/request_review')

    steps:
      - name: Set up GitHub CLI
        uses: actions/setup-gh@v2
        with:
          gh-version: 2

      - name: Debug - Environment Info
        run: |
          env
          echo "GitHub Event:"
          cat $GITHUB_EVENT_PATH
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
        
      - name: Debug - List Files
        run: |
          ls -al
        
      - name: Debug - Check PR Number
        run: |
          pr_number=${{ github.event.issue.number }}
          echo "PR Number: $pr_number"
        
      - name: Add label and request review
        run: |
          pr_number=${{ github.event.issue.number }}

          echo "Adding label 'review-requested' to the PR"
          gh pr edit $pr_number --add-label "review-requested"

          echo "Requesting review from @cryostatio/reviewer(s) team"
          gh pr request-review $pr_number --team cryostatio/reviewer(s)

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug - List PR
        run: |
          gh pr list
        
      - name: Remove label on review
        run: |
          pr_number=${{ github.event.issue.number }}
          reviews_status=$(gh pr list --json state,reviews -q ".[] | select(.number == $pr_number) | .reviews[].state")
          if [[ -n "$reviews_status" ]]; then
            echo "Changes requested, removing 'review-requested' label"
            gh pr edit $pr_number --remove-label "review-requested"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
