name: Request Review

on:
  issue_comment:
    types:
      - created

jobs:
  request-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/request_review')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Add label and request review
        run: |
          reviewers="@cryostatio/reviewers"
          pr_number=${{ github.event.issue.number }}

          echo "Adding label 'review-requested' to the PR"
          gh pr edit $pr_number --add-label "review-requested"

          if [ -n "$reviewers" ]; then
            gh pr create --reviewer $reviewers
          else
            echo "Requesting review from @cryostatio/reviewers team"
            gh pr create --reviewer cryostatio/reviewers
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#test23
