name: Request Review

on:
  issue_comment:
    types:
      - created

jobs:
  request-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/request_review')

    steps:
      - name: Set up GitHub CLI
        uses: actions/setup-gh@v2
        with:
          gh-version: 2

      - name: Add label
        run: |
          pr_number=${{ github.event.issue.number }}

          echo "Adding label 'review-requested' to the PR"
          gh pr edit $pr_number --add-label "review-requested"
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
