name: Request Review

on:
  issue_comment:
    types:
      - created

jobs:
  request-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/request_review')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Add label and request review
        run: |
          reviewers="mwangggg"

          echo "Adding label 'review-requested' to the PR"
          gh pr edit ${{ github.event.issue.number }} --add-label "review-requested"

            echo "Requesting review from @cryostatio/reviewers team"
          for reviewer in $reviewers; do
            gh pr edit ${{ github.event.issue.number }} --add-reviewer $reviewer
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

